name: MinecartRevolutionTags
version: 1.0
description: MinecartRevolutionTags is a plugin for MinecartRevolution which adds the TrainCarts tag system.
authors: [QuarterCode, LoadingByte]
website: http://dev.bukkit.org/server-mods/MinecartRevolutionTags
main: com.quartercode.minecartrevolutiontags.MinecartRevolutionTags
depend: [MinecartRevolution]



permissions:
  minecartrevolutiontags.*:
    description: Gives access to use all MinecartRevolutionTags functions
    default: op
    children:
      minecartrevolutiontags.control.sign.*: true



  minecartrevolutiontags.control.sign.*:
    description: Gives access to use all MinecartRevolutionTags control signs
    children:
      minecartrevolutiontags.control.sign.tag.*: true
      minecartrevolutiontags.control.sign.tagterm.*: true


  minecartrevolution.control.sign.tag.*:
    description: Gives access to use the MinecartRevolutionTags Tag sign
    children:
      minecartrevolution.control.sign.tag.place: true
      minecartrevolution.control.sign.tag.destroy: true
  minecartrevolution.control.sign.tag.place:
    description: Gives access to place the MinecartRevolutionTags Tag sign
  minecartrevolution.control.sign.tag.destroy:
    description: Gives access to destroy the MinecartRevolutionTags Tag sign
